package com.publiccms.entities.cms;

// Generated 2015-7-10 16:31:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsContentTag generated by hbm2java
 */
@Entity
@Table(name = "cms_content_tag")
public class CmsContentTag implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private int tagId;
    private int contentId;

    public CmsContentTag() {
    }

    public CmsContentTag(int tagId, int contentId) {
        this.tagId = tagId;
        this.contentId = contentId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "tag_id", nullable = false)
    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    @Column(name = "content_id", nullable = false)
    public int getContentId() {
        return this.contentId;
    }

    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

}
