package org.publiccms.entities.home;
// Generated 2016-11-12 18:33:49 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * HomeAttentionId generated by hbm2java
 */
@Embeddable
public class HomeAttentionId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "用户")
    private long userId;
    @GeneratorColumn(title = "关注用户")
    private long attentionId;

    public HomeAttentionId() {
    }

    public HomeAttentionId(long userId, long attentionId) {
        this.userId = userId;
        this.attentionId = attentionId;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "attention_id", nullable = false)
    public long getAttentionId() {
        return this.attentionId;
    }

    public void setAttentionId(long attentionId) {
        this.attentionId = attentionId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof HomeAttentionId))
            return false;
        HomeAttentionId castOther = (HomeAttentionId) other;

        return (this.getUserId() == castOther.getUserId()) && (this.getAttentionId() == castOther.getAttentionId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getUserId();
        result = 37 * result + (int) this.getAttentionId();
        return result;
    }

}
