package com.publiccms.entities.cms;
// Generated 2016-11-19 15:33:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.sanluan.common.generator.annotation.GeneratorColumn;

/**
 * CmsContentTagId generated by hbm2java
 */
@Embeddable
public class CmsContentTagId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "标签")
    private long tagId;
    @GeneratorColumn(title = "内容")
    private long contentId;

    public CmsContentTagId() {
    }

    public CmsContentTagId(long tagId, long contentId) {
        this.tagId = tagId;
        this.contentId = contentId;
    }

    @Column(name = "tag_id", nullable = false)
    public long getTagId() {
        return this.tagId;
    }

    public void setTagId(long tagId) {
        this.tagId = tagId;
    }

    @Column(name = "content_id", nullable = false)
    public long getContentId() {
        return this.contentId;
    }

    public void setContentId(long contentId) {
        this.contentId = contentId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CmsContentTagId))
            return false;
        CmsContentTagId castOther = (CmsContentTagId) other;

        return (this.getTagId() == castOther.getTagId()) && (this.getContentId() == castOther.getContentId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getTagId();
        result = 37 * result + (int) this.getContentId();
        return result;
    }

}
