package com.publiccms.entities.cms;

// Generated 2015-6-25 11:28:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsCategoryAttribute generated by hbm2java
 */
@Entity
@Table(name = "cms_category_attribute")
public class CmsCategoryAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int categoryId;
    private String data;

    public CmsCategoryAttribute() {
    }

    public CmsCategoryAttribute(int categoryId) {
        this.categoryId = categoryId;
    }

    public CmsCategoryAttribute(int categoryId, String data) {
        this.categoryId = categoryId;
        this.data = data;
    }

    @Id
    @Column(name = "category_id", unique = true, nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "data", length = 65535)
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
