package com.publiccms.entities.log;
// Generated 2021-8-6 14:20:45 by Hibernate Tools 5.4.32.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * LogVisitUrl generated by hbm2java
 */
@Entity
@Table(name = "log_visit_url")
public class LogVisitUrl implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private LogVisitUrlId id;
    @GeneratorColumn(title = "URL")
    private String url;
    @GeneratorColumn(title = "PV")
    private long pv;
    @GeneratorColumn(title = "UV")
    private Long uv;
    @GeneratorColumn(title = "IP Views")
    private Long ipviews;

    public LogVisitUrl() {
    }

    public LogVisitUrl(LogVisitUrlId id, String url, long pv) {
        this.id = id;
        this.url = url;
        this.pv = pv;
    }

    public LogVisitUrl(short siteId, Date visitDate, String url, long pv, Long uv, Long ipviews) {
        this.id = new LogVisitUrlId(siteId, visitDate, null, null);
        this.url = url;
        this.pv = pv;
        this.uv = uv;
        this.ipviews = ipviews;
    }

    public LogVisitUrl(LogVisitUrlId id, String url, long pv, Long uv, Long ipviews) {
        this.id = id;
        this.url = url;
        this.pv = pv;
        this.uv = uv;
        this.ipviews = ipviews;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "siteId", column = @Column(name = "site_id", nullable = false)),
            @AttributeOverride(name = "visitDate", column = @Column(name = "visit_date", nullable = false, length = 10)),
            @AttributeOverride(name = "urlMd5", column = @Column(name = "url_md5", nullable = false, length = 50)),
            @AttributeOverride(name = "urlSha256", column = @Column(name = "url_sha256", nullable = false, length = 100)) })
    public LogVisitUrlId getId() {
        return this.id;
    }

    public void setId(LogVisitUrlId id) {
        this.id = id;
    }

    @Column(name = "url", nullable = false, length = 2048)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "pv", nullable = false)
    public long getPv() {
        return this.pv;
    }

    public void setPv(long pv) {
        this.pv = pv;
    }

    @Column(name = "uv")
    public Long getUv() {
        return this.uv;
    }

    public void setUv(Long uv) {
        this.uv = uv;
    }

    @Column(name = "ipviews")
    public Long getIpviews() {
        return this.ipviews;
    }

    public void setIpviews(Long ipviews) {
        this.ipviews = ipviews;
    }

}
