package com.publiccms.entities.cms;

// Generated 2016-1-25 10:16:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsContentRelated generated by hbm2java
 */
@Entity
@Table(name = "cms_content_related")
public class CmsContentRelated implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "ID")
    private Integer id;
    @MyColumn(title = "内容", condition = true)
    private int contentId;
    @MyColumn(title = "推荐内容", condition = true)
    private Integer relatedContentId;
    @MyColumn(title = "推荐用户", condition = true)
    private int userId;
    @MyColumn(title = "推荐地址")
    private String url;
    @MyColumn(title = "推荐标题")
    private String title;
    @MyColumn(title = "推荐描述")
    private String description;
    @MyColumn(title = "点击数", order = true)
    private int clicks;
    @MyColumn(title = "排序")
    private int sort;

    public CmsContentRelated() {
    }

    public CmsContentRelated(int contentId, int userId, int clicks, int sort) {
        this.contentId = contentId;
        this.userId = userId;
        this.clicks = clicks;
        this.sort = sort;
    }

    public CmsContentRelated(int contentId, Integer relatedContentId, int userId, String url, String title, String description,
            int clicks, int sort) {
        this.contentId = contentId;
        this.relatedContentId = relatedContentId;
        this.userId = userId;
        this.url = url;
        this.title = title;
        this.description = description;
        this.clicks = clicks;
        this.sort = sort;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "content_id", nullable = false)
    public int getContentId() {
        return this.contentId;
    }

    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

    @Column(name = "related_content_id")
    public Integer getRelatedContentId() {
        return this.relatedContentId;
    }

    public void setRelatedContentId(Integer relatedContentId) {
        this.relatedContentId = relatedContentId;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "url", length = 2048)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "title")
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "description", length = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "clicks", nullable = false)
    public int getClicks() {
        return this.clicks;
    }

    public void setClicks(int clicks) {
        this.clicks = clicks;
    }

    @Column(name = "sort", nullable = false)
    public int getSort() {
        return this.sort;
    }

    public void setSort(int sort) {
        this.sort = sort;
    }

}
