package com.publiccms.entities.cms;

// Generated 2016-1-25 10:16:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsContentFiles generated by hbm2java
 */
@Entity
@Table(name = "cms_content_file")
public class CmsContentFile implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "ID")
    private Integer id;
    @MyColumn(title = "内容", condition = true)
    private int contentId;
    @MyColumn(title = "上传用户", condition = true)
    private int userId;
    @MyColumn(title = "文件路径")
    private String filePath;
    @MyColumn(title = "是否图片", condition = true)
    private boolean image;
    @MyColumn(title = "大小", order = true)
    private int size;
    @MyColumn(title = "点击", order = true)
    private int clicks;
    @MyColumn(title = "排序")
    private int sort;
    @MyColumn(title = "描述")
    private String description;

    public CmsContentFile() {
    }

    public CmsContentFile(int contentId, int userId, String filePath, boolean image, int size, int clicks, int sort) {
        this.contentId = contentId;
        this.userId = userId;
        this.filePath = filePath;
        this.image = image;
        this.size = size;
        this.clicks = clicks;
        this.sort = sort;
    }

    public CmsContentFile(int contentId, int userId, String filePath, boolean image, int size, int clicks, int sort,
            String description) {
        this.contentId = contentId;
        this.userId = userId;
        this.filePath = filePath;
        this.image = image;
        this.size = size;
        this.clicks = clicks;
        this.sort = sort;
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "content_id", nullable = false)
    public int getContentId() {
        return this.contentId;
    }

    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "file_path", nullable = false)
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "image", nullable = false)
    public boolean isImage() {
        return this.image;
    }

    public void setImage(boolean image) {
        this.image = image;
    }

    @Column(name = "size", nullable = false)
    public int getSize() {
        return this.size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    @Column(name = "clicks", nullable = false)
    public int getClicks() {
        return this.clicks;
    }

    public void setClicks(int clicks) {
        this.clicks = clicks;
    }

    @Column(name = "sort", nullable = false)
    public int getSort() {
        return this.sort;
    }

    public void setSort(int sort) {
        this.sort = sort;
    }

    @Column(name = "description", length = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
