package com.publiccms.entities.log;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sanluan.common.source.entity.MyColumn;

/**
 * LogOperate generated by hbm2java
 */
@Entity
@Table(name = "log_operate")
public class LogOperate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "ID")
    private Long id;
    @MyColumn(title = "站点", condition = true)
    private int siteId;
    @MyColumn(title = "用户", condition = true)
    private long userId;
    @MyColumn(title = "渠道", condition = true)
    private String channel;
    @MyColumn(title = "操作", condition = true)
    private String operate;
    @MyColumn(title = "IP", condition = true)
    private String ip;
    @MyColumn(title = "操作日期", condition = true, order = true)
    private Date createDate;
    @MyColumn(title = "内容", condition = true, like = true)
    private String content;

    public LogOperate() {
    }

    public LogOperate(int siteId, long userId, String channel, String operate, Date createDate, String content) {
        this.siteId = siteId;
        this.userId = userId;
        this.channel = channel;
        this.operate = operate;
        this.createDate = createDate;
        this.content = content;
    }

    public LogOperate(int siteId, long userId, String channel, String operate, String ip, Date createDate, String content) {
        this.siteId = siteId;
        this.userId = userId;
        this.channel = channel;
        this.operate = operate;
        this.ip = ip;
        this.createDate = createDate;
        this.content = content;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "site_id", nullable = false)
    public int getSiteId() {
        return this.siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "channel", nullable = false, length = 50)
    public String getChannel() {
        return this.channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    @Column(name = "operate", nullable = false, length = 40)
    public String getOperate() {
        return this.operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    @Column(name = "ip", length = 64)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "content", nullable = false, length = 500)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
