package com.publiccms.entities.trade;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.util.Date;

import com.publiccms.common.generator.annotation.GeneratorColumn;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * TradeUserCoupon generated by hbm2java
 */
@Entity
@Table(name = "trade_user_coupon")
public class TradeUserCoupon implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private TradeUserCouponId id;
    private int status;
    private Date createDate;
    private String startDate;
    private String expiryDate;

    public TradeUserCoupon() {
    }

    public TradeUserCoupon(TradeUserCouponId id, int status, Date createDate, String startDate) {
        this.id = id;
        this.status = status;
        this.createDate = createDate;
        this.startDate = startDate;
    }

    public TradeUserCoupon(TradeUserCouponId id, int status, Date createDate, String startDate, String expiryDate) {
        this.id = id;
        this.status = status;
        this.createDate = createDate;
        this.startDate = startDate;
        this.expiryDate = expiryDate;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
            @AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)) })
    public TradeUserCouponId getId() {
        return this.id;
    }

    public void setId(TradeUserCouponId id) {
        this.id = id;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "start_date", nullable = false)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Column(name = "expiry_date")
    public String getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

}
