package com.publiccms.entities.trade;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TradeUserCoupon generated by hbm2java
 */
@Entity
@Table(name = "trade_user_coupon")
public class TradeUserCoupon implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long id;
    private String userId;
    private String couponId;
    private int status;
    private Date createDate;
    private String startDate;
    private String expiryDate;

    public TradeUserCoupon() {
    }

    public TradeUserCoupon(String userId, String couponId, int status, Date createDate, String startDate) {
        this.userId = userId;
        this.couponId = couponId;
        this.status = status;
        this.createDate = createDate;
        this.startDate = startDate;
    }

    public TradeUserCoupon(String userId, String couponId, int status, Date createDate, String startDate, String expiryDate) {
        this.userId = userId;
        this.couponId = couponId;
        this.status = status;
        this.createDate = createDate;
        this.startDate = startDate;
        this.expiryDate = expiryDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "user_id", nullable = false)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "coupon_id", nullable = false)
    public String getCouponId() {
        return this.couponId;
    }

    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "start_date", nullable = false)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Column(name = "expiry_date")
    public String getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

}
