package com.publiccms.entities.trade;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * TradeCoupon generated by hbm2java
 */
@Entity
@Table(name = "trade_coupon")
public class TradeCoupon implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    /**
     * id
     */
    @GeneratorColumn(title = "ID")
    private Long id;
    @GeneratorColumn(title = "站点", condition = true)
    @JsonIgnore
    private short siteId;
    private String name;
    private Integer categoryId;
    private Long contentId;
    private String startDate;
    private String expiryDate;
    private BigDecimal startingAmount;
    private BigDecimal discount;
    private BigDecimal price;
    private int type;
    private String redeemCode;
    private int count;
    private String createDate;
    private boolean disabled;

    public TradeCoupon() {
    }

    public TradeCoupon(short siteId, String name, String startDate, int type, int count, boolean disabled) {
        this.siteId = siteId;
        this.name = name;
        this.startDate = startDate;
        this.type = type;
        this.count = count;
        this.disabled = disabled;
    }

    public TradeCoupon(short siteId, String name, Integer categoryId, Long contentId, String startDate, String expiryDate,
            BigDecimal startingAmount, BigDecimal discount, BigDecimal price, int type, String redeemCode, int count,
            String createDate, boolean disabled) {
        this.siteId = siteId;
        this.name = name;
        this.categoryId = categoryId;
        this.contentId = contentId;
        this.startDate = startDate;
        this.expiryDate = expiryDate;
        this.startingAmount = startingAmount;
        this.discount = discount;
        this.price = price;
        this.type = type;
        this.redeemCode = redeemCode;
        this.count = count;
        this.createDate = createDate;
        this.disabled = disabled;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "site_id", nullable = false)
    public short getSiteId() {
        return this.siteId;
    }

    public void setSiteId(short siteId) {
        this.siteId = siteId;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "category_id")
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "content_id")
    public Long getContentId() {
        return this.contentId;
    }

    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    @Column(name = "start_date", nullable = false)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Column(name = "expiry_date")
    public String getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Column(name = "starting_amount", precision = 10)
    public BigDecimal getStartingAmount() {
        return this.startingAmount;
    }

    public void setStartingAmount(BigDecimal startingAmount) {
        this.startingAmount = startingAmount;
    }

    @Column(name = "discount", precision = 10, scale = 1)
    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    @Column(name = "price", precision = 10)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "type", nullable = false)
    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @Column(name = "redeem_code")
    public String getRedeemCode() {
        return this.redeemCode;
    }

    public void setRedeemCode(String redeemCode) {
        this.redeemCode = redeemCode;
    }

    @Column(name = "count", nullable = false)
    public int getCount() {
        return this.count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    @Column(name = "create_date")
    public String getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    @Column(name = "disabled", nullable = false)
    public boolean isDisabled() {
        return this.disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

}
