package org.publiccms.entities.cms;
// Generated 2016-7-31 0:08:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * CmsLotteryUserAttribute generated by hbm2java
 */
@Entity
@Table(name = "cms_lottery_user_attribute")
public class CmsLotteryUserAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "抽奖用户")
    private long lotteryUserId;
    @GeneratorColumn(title = "扩展数据")
    private String data;

    public CmsLotteryUserAttribute() {
    }

    public CmsLotteryUserAttribute(long lotteryUserId) {
        this.lotteryUserId = lotteryUserId;
    }

    public CmsLotteryUserAttribute(long lotteryUserId, String data) {
        this.lotteryUserId = lotteryUserId;
        this.data = data;
    }

    @Id

    @Column(name = "lottery_user_id", unique = true, nullable = false)
    public long getLotteryUserId() {
        return this.lotteryUserId;
    }

    public void setLotteryUserId(long lotteryUserId) {
        this.lotteryUserId = lotteryUserId;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
