package com.publiccms.entities.system;

// Generated 2015-7-22 13:41:01 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * SystemMoudle generated by hbm2java
 */
@Entity
@Table(name = "system_moudle")
public class SystemMoudle implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    @MyColumn(title = "名称")
    private String name;
    @MyColumn(title = "地址", condition = true)
    private String url;
    private String authorizedUrl;
    @MyColumn(title = "父模块", condition = true)
    private Integer parentId;

    public SystemMoudle() {
    }

    public SystemMoudle(String name, String url) {
        this.name = name;
        this.url = url;
    }

    public SystemMoudle(String name, String url, String authorizedUrl, Integer parentId) {
        this.name = name;
        this.url = url;
        this.authorizedUrl = authorizedUrl;
        this.parentId = parentId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "url", nullable = false)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "authorized_url", length = 65535)
    public String getAuthorizedUrl() {
        return this.authorizedUrl;
    }

    public void setAuthorizedUrl(String authorizedUrl) {
        this.authorizedUrl = authorizedUrl;
    }

    @Column(name = "parent_id")
    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

}
