package com.publiccms.entities.system;

// Generated 2015-7-24 16:51:35 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemRoleAuthorized generated by hbm2java
 */
@Entity
@Table(name = "system_role_authorized")
public class SystemRoleAuthorized implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private int roleId;
    private String authorizedUrl;

    public SystemRoleAuthorized() {
    }

    public SystemRoleAuthorized(int roleId, String authorizedUrl) {
        this.roleId = roleId;
        this.authorizedUrl = authorizedUrl;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "role_id", nullable = false)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Column(name = "authorized_url", nullable = false)
    public String getAuthorizedUrl() {
        return this.authorizedUrl;
    }

    public void setAuthorizedUrl(String authorizedUrl) {
        this.authorizedUrl = authorizedUrl;
    }

}
