package com.publiccms.entities.sys;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysCertification generated by hbm2java
 */
@Entity
@Table(name="sys_certification")
public class SysCertification  implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

     private Integer id;
     private byte siteId;
     private String name;
     private String cover;
     private String description;
     private boolean allowApply;
     private Date createDate;
     private boolean disabled;
     private Integer extendId;

    public SysCertification() {
    }

	
    public SysCertification(byte siteId, String name, boolean allowApply, Date createDate, boolean disabled) {
        this.siteId = siteId;
        this.name = name;
        this.allowApply = allowApply;
        this.createDate = createDate;
        this.disabled = disabled;
    }
    public SysCertification(byte siteId, String name, String cover, String description, boolean allowApply, Date createDate, boolean disabled, Integer extendId) {
       this.siteId = siteId;
       this.name = name;
       this.cover = cover;
       this.description = description;
       this.allowApply = allowApply;
       this.createDate = createDate;
       this.disabled = disabled;
       this.extendId = extendId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="site_id", nullable=false)
    public byte getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(byte siteId) {
        this.siteId = siteId;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="cover")
    public String getCover() {
        return this.cover;
    }
    
    public void setCover(String cover) {
        this.cover = cover;
    }

    
    @Column(name="description", length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="allow_apply", nullable=false)
    public boolean isAllowApply() {
        return this.allowApply;
    }
    
    public void setAllowApply(boolean allowApply) {
        this.allowApply = allowApply;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="disabled", nullable=false)
    public boolean isDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    
    @Column(name="extend_id")
    public Integer getExtendId() {
        return this.extendId;
    }
    
    public void setExtendId(Integer extendId) {
        this.extendId = extendId;
    }




}


