package com.publiccms.entities.sys;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * SysDeptmItem generated by hbm2java
 */
@Entity
@Table(name = "sys_dept_item")
@DynamicUpdate
public class SysDeptItem implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * id
     */
    @GeneratorColumn(title = "ID")
    private SysDeptItemId id;

    public SysDeptItem() {
    }

    public SysDeptItem(SysDeptItemId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "deptId", column = @Column(name = "dept_id", nullable = false)),
            @AttributeOverride(name = "itemType", column = @Column(name = "item_type", nullable = false)),
            @AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)) })
    public SysDeptItemId getId() {
        return this.id;
    }

    public void setId(SysDeptItemId id) {
        this.id = id;
    }

}
