package com.publiccms.entities.sys;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;

// Generated 2016-1-19 11:28:06 by Hibernate Tools 4.3.1

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * SysRoleUser generated by hbm2java
 */
@Entity
@Table(name = "sys_role_user")
@DynamicUpdate
public class SysRoleUser implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private SysRoleUserId id;

    public SysRoleUser() {
    }

    public SysRoleUser(SysRoleUserId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
            @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
    public SysRoleUserId getId() {
        return this.id;
    }

    public void setId(SysRoleUserId id) {
        this.id = id;
    }

}
