package com.publiccms.entities.sys;
// Generated 2021-8-2 11:20:41 by Hibernate Tools 5.4.32.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SysSiteDatasource generated by hbm2java
 */
@Entity
@Table(name = "sys_site_datasource")
public class SysSiteDatasource implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    /**
     * id
     */
    private SysSiteDatasourceId id;

    public SysSiteDatasource() {
    }

    public SysSiteDatasource(SysSiteDatasourceId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "siteId", column = @Column(name = "site_id", nullable = false)),
            @AttributeOverride(name = "datasource", column = @Column(name = "datasource", nullable = false, length = 50)) })
    public SysSiteDatasourceId getId() {
        return this.id;
    }

    public void setId(SysSiteDatasourceId id) {
        this.id = id;
    }

}
