package com.publiccms.entities.sys;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysWorkflowProcess generated by hbm2java
 */
@Entity
@Table(name = "sys_workflow_process")
public class SysWorkflowProcess implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long id;
    private short siteId;
    private String itemType;
    private String itemId;
    private long stepId;
    private String operate;
    private String reason;
    private boolean closed;
    private Date createDate;

    public SysWorkflowProcess() {
    }

    public SysWorkflowProcess(long id, short siteId, String itemType, String itemId, long stepId, String operate, boolean closed,
            Date createDate) {
        this.id = id;
        this.siteId = siteId;
        this.itemType = itemType;
        this.itemId = itemId;
        this.stepId = stepId;
        this.operate = operate;
        this.closed = closed;
        this.createDate = createDate;
    }

    public SysWorkflowProcess(long id, short siteId, String itemType, String itemId, long stepId, String operate, String reason,
            boolean closed, Date createDate) {
        this.id = id;
        this.siteId = siteId;
        this.itemType = itemType;
        this.itemId = itemId;
        this.stepId = stepId;
        this.operate = operate;
        this.reason = reason;
        this.closed = closed;
        this.createDate = createDate;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "site_id", nullable = false)
    public short getSiteId() {
        return this.siteId;
    }

    public void setSiteId(short siteId) {
        this.siteId = siteId;
    }

    @Column(name = "item_type", nullable = false, length = 50)
    public String getItemType() {
        return this.itemType;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    @Column(name = "item_id", nullable = false, length = 100)
    public String getItemId() {
        return this.itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    @Column(name = "step_id", nullable = false)
    public long getStepId() {
        return this.stepId;
    }

    public void setStepId(long stepId) {
        this.stepId = stepId;
    }

    @Column(name = "operate", nullable = false, length = 20)
    public String getOperate() {
        return this.operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    @Column(name = "reason")
    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Column(name = "closed", nullable = false)
    public boolean isClosed() {
        return this.closed;
    }

    public void setClosed(boolean closed) {
        this.closed = closed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
