package com.publiccms.entities.sys;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.util.Date;

import org.hibernate.annotations.DynamicUpdate;

import com.publiccms.common.generator.annotation.GeneratorColumn;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * SysWorkflowProcess generated by hbm2java
 */
@Entity
@Table(name = "sys_workflow_process_history")
@DynamicUpdate
public class SysWorkflowProcessHistory implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    /**
     * id
     */
    @GeneratorColumn(title = "ID")
    private Long id;
    @GeneratorColumn(title = "流程", condition = true)
    private Long processId;
    /**
     * step
     * <p>
     * 步骤
     */
    @GeneratorColumn(title = "步骤")
    private long stepId;
    /**
     * user
     * <p>
     * 用户
     */
    @GeneratorColumn(title = "用户", condition = true)
    private long userId;
    /**
     * operate
     * <p>
     * 操作
     */
    @GeneratorColumn(title = "操作")
    private String operate;
    /**
     * reason
     * <p>
     * 原因
     */
    @GeneratorColumn(title = "原因")
    private String reason;
    /**
     * create date
     * <p>
     * 创建日期
     */
    @GeneratorColumn(title = "创建日期")
    private Date createDate;

    public SysWorkflowProcessHistory() {
    }

    public SysWorkflowProcessHistory(long processId, long stepId, long userId, String operate, Date createDate) {
        this.processId = processId;
        this.stepId = stepId;
        this.userId = userId;
        this.operate = operate;
        this.createDate = createDate;
    }

    public SysWorkflowProcessHistory(long processId, long stepId, long userId, String operate, String reason, Date createDate) {
        this.processId = processId;
        this.stepId = stepId;
        this.userId = userId;
        this.operate = operate;
        this.reason = reason;
        this.createDate = createDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "process_id", nullable = false)
    public long getProcessId() {
        return this.processId;
    }

    public void setProcessId(long processId) {
        this.processId = processId;
    }

    @Column(name = "step_id", nullable = false)
    public long getStepId() {
        return this.stepId;
    }

    public void setStepId(long stepId) {
        this.stepId = stepId;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "operate", nullable = false, length = 20)
    public String getOperate() {
        return this.operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    @Column(name = "reason")
    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
