package com.publiccms.entities.sys;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysWorkflow generated by hbm2java
 */
@Entity
@Table(name = "sys_workflow")
public class SysWorkflow implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int id;
    private short siteId;
    private String name;
    private String description;
    private int steps;
    private long userId;
    private Date updateDate;
    private Date createDate;
    private boolean disabled;

    public SysWorkflow() {
    }

    public SysWorkflow(int id, short siteId, String name, int steps, long userId, Date createDate, boolean disabled) {
        this.id = id;
        this.siteId = siteId;
        this.name = name;
        this.steps = steps;
        this.userId = userId;
        this.createDate = createDate;
        this.disabled = disabled;
    }

    public SysWorkflow(int id, short siteId, String name, String description, int steps, long userId, Date updateDate,
            Date createDate, boolean disabled) {
        this.id = id;
        this.siteId = siteId;
        this.name = name;
        this.description = description;
        this.steps = steps;
        this.userId = userId;
        this.updateDate = updateDate;
        this.createDate = createDate;
        this.disabled = disabled;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "site_id", nullable = false)
    public short getSiteId() {
        return this.siteId;
    }

    public void setSiteId(short siteId) {
        this.siteId = siteId;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "steps", nullable = false)
    public int getSteps() {
        return this.steps;
    }

    public void setSteps(int steps) {
        this.steps = steps;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "disabled", nullable = false)
    public boolean isDisabled() {
        return this.disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

}
