package com.publiccms.entities.sys;
// Generated 2023-8-7 21:42:23 by Hibernate Tools 5.6.15.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysWorkflowStep generated by hbm2java
 */
@Entity
@Table(name = "sys_workflow_step")
public class SysWorkflowStep implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long id;
    private int workflowId;
    private String roleIds;
    private String deptIds;
    private String userIds;
    private int sort;

    public SysWorkflowStep() {
    }

    public SysWorkflowStep(long id, int workflowId, int sort) {
        this.id = id;
        this.workflowId = workflowId;
        this.sort = sort;
    }

    public SysWorkflowStep(long id, int workflowId, String roleIds, String deptIds, String userIds, int sort) {
        this.id = id;
        this.workflowId = workflowId;
        this.roleIds = roleIds;
        this.deptIds = deptIds;
        this.userIds = userIds;
        this.sort = sort;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "workflow_id", nullable = false)
    public int getWorkflowId() {
        return this.workflowId;
    }

    public void setWorkflowId(int workflowId) {
        this.workflowId = workflowId;
    }

    @Column(name = "role_ids", length = 65535)
    public String getRoleIds() {
        return this.roleIds;
    }

    public void setRoleIds(String roleIds) {
        this.roleIds = roleIds;
    }

    @Column(name = "dept_ids", length = 65535)
    public String getDeptIds() {
        return this.deptIds;
    }

    public void setDeptIds(String deptIds) {
        this.deptIds = deptIds;
    }

    @Column(name = "user_ids", length = 65535)
    public String getUserIds() {
        return this.userIds;
    }

    public void setUserIds(String userIds) {
        this.userIds = userIds;
    }

    @Column(name = "sort", nullable = false)
    public int getSort() {
        return this.sort;
    }

    public void setSort(int sort) {
        this.sort = sort;
    }

}
