package com.publiccms.entities.home;
// Generated 2016-7-31 0:08:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HomeMessage generated by hbm2java
 */
@Entity
@Table(name = "home_message")
public class HomeMessage implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Long id;
    private long userId;
    private long sendUserId;
    private long receiveUserId;
    private Long messageId;
    private String channel;
    private Date createDate;
    private String content;

    public HomeMessage() {
    }

    public HomeMessage(long userId, long sendUserId, long receiveUserId, String channel, Date createDate, String content) {
        this.userId = userId;
        this.sendUserId = sendUserId;
        this.receiveUserId = receiveUserId;
        this.channel = channel;
        this.createDate = createDate;
        this.content = content;
    }

    public HomeMessage(long userId, long sendUserId, long receiveUserId, Long messageId, String channel, Date createDate,
            String content) {
        this.userId = userId;
        this.sendUserId = sendUserId;
        this.receiveUserId = receiveUserId;
        this.messageId = messageId;
        this.channel = channel;
        this.createDate = createDate;
        this.content = content;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "send_user_id", nullable = false)
    public long getSendUserId() {
        return this.sendUserId;
    }

    public void setSendUserId(long sendUserId) {
        this.sendUserId = sendUserId;
    }

    @Column(name = "receive_user_id", nullable = false)
    public long getReceiveUserId() {
        return this.receiveUserId;
    }

    public void setReceiveUserId(long receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    @Column(name = "message_id")
    public Long getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    @Column(name = "channel", nullable = false, length = 50)
    public String getChannel() {
        return this.channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "content", nullable = false, length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
