configurations {
    instrumentedJars {
        extendsFrom implementation
    }
}

dependencies {
    implementation project(path:':publiccms-core', configuration: 'instrumentedJars')
    implementation project(':publiccms-core')

    implementation "org.apache.lucene:lucene-analysis-smartcn:${luceneVersion}"
    // https://mvnrepository.com/artifact/org.lionsoul/ip2region
    implementation 'org.lionsoul:ip2region:3.3.7'implementation "com.github.therapi:therapi-runtime-javadoc:${therapiJavadocVersion}"

    annotationProcessor "com.github.therapi:therapi-runtime-javadoc-scribe:${therapiJavadocVersion}"
    compileOnly "jakarta.servlet:jakarta.servlet-api:${servletVersion}"
}