package com.publiccms.entities.plugin;
// Generated 2016-7-31 0:08:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * PluginLotteryUserAttribute generated by hbm2java
 */
@Entity
@Table(name = "plugin_lottery_user_attribute")
public class PluginLotteryUserAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "抽奖用户")
    private long lotteryUserId;
    @MyColumn(title = "扩展数据")
    private String data;

    public PluginLotteryUserAttribute() {
    }

    public PluginLotteryUserAttribute(long lotteryUserId) {
        this.lotteryUserId = lotteryUserId;
    }

    public PluginLotteryUserAttribute(long lotteryUserId, String data) {
        this.lotteryUserId = lotteryUserId;
        this.data = data;
    }

    @Id

    @Column(name = "lottery_user_id", unique = true, nullable = false)
    public long getLotteryUserId() {
        return this.lotteryUserId;
    }

    public void setLotteryUserId(long lotteryUserId) {
        this.lotteryUserId = lotteryUserId;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
