package com.publiccms.entities.plugin;

// Generated 2016-3-1 16:21:35 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.sanluan.common.source.entity.MyColumn;

/**
 * PluginSite generated by hbm2java
 */
@Entity
@Table(name = "plugin_site", uniqueConstraints = @UniqueConstraint(columnNames = { "site_id", "plugin_code" }))
public class PluginSite implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "ID")
    private Integer id;
    @MyColumn(title = "站点", condition = true)
    private int siteId;
    @MyColumn(title = "插件", condition = true)
    private String pluginCode;
    @MyColumn(title = "插件模板")
    private String widgetTemplate;
    @MyColumn(title = "静态化模板")
    private String staticTemplate;
    @MyColumn(title = "路径")
    private String path;

    public PluginSite() {
    }

    public PluginSite(int siteId, String pluginCode) {
        this.siteId = siteId;
        this.pluginCode = pluginCode;
    }

    public PluginSite(int siteId, String pluginCode, String widgetTemplate, String staticTemplate, String path) {
        this.siteId = siteId;
        this.pluginCode = pluginCode;
        this.widgetTemplate = widgetTemplate;
        this.staticTemplate = staticTemplate;
        this.path = path;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "site_id", nullable = false)
    public int getSiteId() {
        return this.siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    @Column(name = "plugin_code", nullable = false, length = 50)
    public String getPluginCode() {
        return this.pluginCode;
    }

    public void setPluginCode(String pluginCode) {
        this.pluginCode = pluginCode;
    }

    @Column(name = "widget_template")
    public String getWidgetTemplate() {
        return this.widgetTemplate;
    }

    public void setWidgetTemplate(String widgetTemplate) {
        this.widgetTemplate = widgetTemplate;
    }

    @Column(name = "static_template")
    public String getStaticTemplate() {
        return this.staticTemplate;
    }

    public void setStaticTemplate(String staticTemplate) {
        this.staticTemplate = staticTemplate;
    }

    @Column(name = "path", length = 2000)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
