package com.publiccms.entities.plugin;
// Generated 2016-7-31 0:08:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * PluginVoteItemAttribute generated by hbm2java
 */
@Entity
@Table(name = "plugin_vote_item_attribute")
public class PluginVoteItemAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "选项ID")
    private long voteItemId;
    @MyColumn(title = "扩展数据")
    private String data;

    public PluginVoteItemAttribute() {
    }

    public PluginVoteItemAttribute(long voteItemId) {
        this.voteItemId = voteItemId;
    }

    public PluginVoteItemAttribute(long voteItemId, String data) {
        this.voteItemId = voteItemId;
        this.data = data;
    }

    @Id

    @Column(name = "vote_item_id", unique = true, nullable = false)
    public long getVoteItemId() {
        return this.voteItemId;
    }

    public void setVoteItemId(long voteItemId) {
        this.voteItemId = voteItemId;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
