package com.publiccms.entities.cms;
// Generated 2026-1-4 13:40:55 by Hibernate Tools 5.6.15.Final

import org.hibernate.validator.constraints.Length;

import com.publiccms.common.generator.annotation.GeneratorColumn;
import com.publiccms.views.pojo.entities.EntityAttribute;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

/**
 * CmsContentLang generated by hbm2java
 */
@Entity
@Table(name = "cms_content_lang")
public class CmsContentLang extends EntityAttribute implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private CmsContentLangId id;
    /**
     * url
     * 
     * 链接地址
     */
    @GeneratorColumn(title = "地址")
    @Length(max = 1000)
    private String url;
    @GeneratorColumn(title = "标题")
    @NotBlank
    @Length(max = 255)
    private String title;
    @GeneratorColumn(title = "作者")
    private String author;
    @GeneratorColumn(title = "编辑")
    private String editor;
    @GeneratorColumn(title = "描述")
    @Length(max = 300)
    private String description;
    @GeneratorColumn(title = "封面")
    private String cover;
    @GeneratorColumn(title = "扩展数据")
    private String data;
    @GeneratorColumn(title = "文本")
    private String text;

    public CmsContentLang() {
    }

    public CmsContentLang(CmsContentLangId id) {
        this.id = id;
    }

    public CmsContentLang(CmsContentLangId id, String url, String title, String author, String editor, String description, String cover,
            String data, String text) {
        this.id = id;
        this.url = url;
        this.title = title;
        this.author = author;
        this.editor = editor;
        this.description = description;
        this.cover = cover;
        this.data = data;
        this.text = text;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "contentId", column = @Column(name = "content_id", nullable = false)),
            @AttributeOverride(name = "lang", column = @Column(name = "lang", nullable = false, length = 50)) })
    public CmsContentLangId getId() {
        return this.id;
    }

    public void setId(CmsContentLangId id) {
        this.id = id;
    }

    @Column(name = "url", length = 1000)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "title")
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "author", length = 50)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "editor", length = 50)
    public String getEditor() {
        return this.editor;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

    @Column(name = "description", length = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "cover")
    public String getCover() {
        return this.cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @Column(name = "text")
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
