package com.publiccms.entities.cms;
// Generated 2026-1-4 13:40:55 by Hibernate Tools 5.6.15.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.validator.constraints.Length;

import com.publiccms.common.generator.annotation.GeneratorColumn;
import com.publiccms.views.pojo.entities.EntityAttribute;

/**
 * CmsCategoryLang generated by hbm2java
 */
@Entity
@Table(name = "cms_category_lang")
@DynamicUpdate
public class CmsCategoryLang extends EntityAttribute implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private CmsCategoryLangId id;
    /**
     * url
     * 
     * 链接地址
     */
    @GeneratorColumn(title = "地址")
    @Length(max = 1000)
    private String url;
    @GeneratorColumn(title = "名称")
    @Length(max = 50)
    private String name;
    @GeneratorColumn(title = "标题")
    @Length(max = 80)
    private String title;
    @GeneratorColumn(title = "关键词")
    @Length(max = 100)
    private String keywords;
    @GeneratorColumn(title = "描述")
    @Length(max = 300)
    private String description;
    @GeneratorColumn(title = "扩展数据")
    private String data;

    public CmsCategoryLang() {
    }

    public CmsCategoryLang(CmsCategoryLangId id, String name) {
        this.id = id;
        this.name = name;
    }

    public CmsCategoryLang(CmsCategoryLangId id, String url, String name, String title, String keywords, String description, String data) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.title = title;
        this.keywords = keywords;
        this.description = description;
        this.data = data;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
            @AttributeOverride(name = "lang", column = @Column(name = "lang", nullable = false, length = 20)) })
    public CmsCategoryLangId getId() {
        return this.id;
    }

    public void setId(CmsCategoryLangId id) {
        this.id = id;
    }

    @Column(name = "url", length = 1000)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "title", length = 80)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "keywords", length = 100)
    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    @Column(name = "description", length = 300)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
