package com.publiccms.entities.cms;
// Generated 2022-3-15 17:51:34 by Hibernate Tools 5.6.2.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * CmsDictionaryExclude generated by hbm2java
 */
@Entity
@Table(name = "cms_dictionary_exclude")
public class CmsDictionaryExclude implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    @GeneratorColumn(title = "ID")
    private CmsDictionaryExcludeId id;

    public CmsDictionaryExclude() {
    }

    public CmsDictionaryExclude(CmsDictionaryExcludeId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "dictionaryId", column = @Column(name = "dictionary_id", nullable = false, length = 20)),
            @AttributeOverride(name = "siteId", column = @Column(name = "site_id", nullable = false)),
            @AttributeOverride(name = "excludeDictionaryId", column = @Column(name = "exclude_dictionary_id", nullable = false, length = 20)) })
    public CmsDictionaryExcludeId getId() {
        return this.id;
    }

    public void setId(CmsDictionaryExcludeId id) {
        this.id = id;
    }

}
