package com.publiccms.entities.cms;
// Generated 2022-3-15 17:51:34 by Hibernate Tools 5.6.2.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * CmsDictionaryExcludeValue generated by hbm2java
 */
@Entity
@Table(name = "cms_dictionary_exclude_value")
public class CmsDictionaryExcludeValue implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    private CmsDictionaryExcludeValueId id;
    @GeneratorColumn(title = "排除的值")
    private String excludeValues;

    public CmsDictionaryExcludeValue() {
    }
    public CmsDictionaryExcludeValue(CmsDictionaryExcludeValueId id) {
        this.id = id;
    }
    public CmsDictionaryExcludeValue(CmsDictionaryExcludeValueId id, String excludeValues) {
        this.id = id;
        this.excludeValues = excludeValues;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "dictionaryId", column = @Column(name = "dictionary_id", nullable = false, length = 20)),
            @AttributeOverride(name = "siteId", column = @Column(name = "site_id", nullable = false)),
            @AttributeOverride(name = "excludeDictionaryId", column = @Column(name = "exclude_dictionary_id", nullable = false, length = 20)),
            @AttributeOverride(name = "value", column = @Column(name = "value", nullable = false, length = 50)) })
    public CmsDictionaryExcludeValueId getId() {
        return this.id;
    }

    public void setId(CmsDictionaryExcludeValueId id) {
        this.id = id;
    }

    @Column(name = "exclude_values", length = 65535)
    public String getExcludeValues() {
        return this.excludeValues;
    }

    public void setExcludeValues(String excludeValues) {
        this.excludeValues = excludeValues;
    }

}
